# Deployment Configuration
---

# Pull Docker Image
- name: Pull nginx-hello image
  docker_image:
    name: dnlwrn/profile-service

# Run Docker Container
- name: Run nginx-hello container
  become: yes
  docker_container:
    name: nginx-hello
    image: dnlwrn/profile-service
    state: started
    detach: true
    exposed_ports:
      - "8000"
    published_ports:
      - "0.0.0.0:8000:80"
    