# Firewall Configuration
---

# enable & deny * connections
- name: Enable ufw
  ufw:
    state: enabled
    policy: deny
  become: yes
  
# start service
- name: Start ufw service
  service:
    name: ufw
    state: started
  become: yes

# enable port access
- name: Allow access to port 8000
  ufw:
    rule: allow
    port: '8000'
    proto: tcp
  become: yes

# enable ssh access
- name: Allow access to port 22
  ufw:
    rule: allow
    port: '22'
    proto: tcp
  become: yes